### ISSUE TITLE
V4 issue

### ISSUE THREAD

**Issue by cesar82** [AlchemyCMS/alchemy-pg_search#32]
Hi guys, I installed the latest version alchemy-pg_search, I have a project with Alchemy brand new, I was waiting for the alchemy-pg_search v4 for Alchemy v6 but I get this error this morning

CanCan::Error in Alchemy::Admin::PagesController#show
The accessible_by call cannot be used with a block 'can' definition.The SQL cannot be determined for :read Alchemy::Page(id: integer, name: string, urlname: string, title: string, language_code: string, language_root: boolean, page_layout: string, meta_keywords: text, meta_description: text, lft: integer, rgt: integer, parent_id: integer, depth: integer, locked_by: integer, restricted: boolean, robot_index: boolean, robot_follow: boolean, sitemap: boolean, layoutpage: boolean, created_at: datetime, updated_at: datetime, creator_id: integer, updater_id: integer, language_id: integer, published_at: datetime, legacy_public_on: datetime, legacy_public_until: datetime, locked_at: datetime, tag_names: )

[cancancan (3.4.0) lib/cancan/ability/rules.rb:75:in `relevant_rules_for_query'](http://localhost:4000/admin/pages/10#)
[cancancan (3.4.0) lib/cancan/ability.rb:172:in `model_adapter'](http://localhost:4000/admin/pages/10#)
[cancancan (3.4.0) lib/cancan/model_additions.rb:25:in `block in accessible_by'](http://localhost:4000/admin/pages/10#)
[cancancan (3.4.0) lib/cancan/config.rb:55:in `with_accessible_by_strategy'](http://localhost:4000/admin/pages/10#)
[cancancan (3.4.0) lib/cancan/model_additions.rb:24:in `accessible_by'](http://localhost:4000/admin/pages/10#)
[alchemy-pg_search (3d9bd0fecb3e) lib/alchemy/pg_search/search.rb:53:in `search'](http://localhost:4000/admin/pages/10#)
[alchemy-pg_search (3d9bd0fecb3e) lib/alchemy-pg_search.rb:33:in `search'](http://localhost:4000/admin/pages/10#)

Do you have any ideas?

**Comment by tvdeyen** [comment]
This is known issue and will be fixed upstream in alchemy soon. 

This issue only happens if you are a logged in user with at least the author role (editor and admins re effected as well). So visitor's of your site will not have the problem.

**Comment by tvdeyen** [comment]
Will be fixed by https://github.com/AlchemyCMS/alchemy_cms/pull/2364

**Comment by tvdeyen** [comment]
@cesar82 until we release a new version you can point Alchemy to our main branch

```rb
# Gemfile
gem "alchemy_cms", github: "AlchemyCMS/alchemy_cms", branch: "main"
```

That should fix the issue

**Comment by cesar82** [comment]
Thanks @tvdeyen , I owe you a beer!!
