### ISSUE TITLE
Can't generate view templates

### ISSUE THREAD

**Issue by wdspkr** [AlchemyCMS/alchemy-pg_search#7]
On ruby 2.3.1, Mac OSX I can't generate the view templates with  `$ bin/rails g alchemy:pg_search:views`. Instead I get the following error message:

```
Could not find "MYRUBY-2.3.1/bundler/gems/alchemy-pg_search-7048f17c75e9/app/views/alchemy/search" in any of your source paths. Please invoke Alchemy::PgSearch::ViewsGenerator.source_root(PATH) with the PATH containing your templates. Currently you have no source paths.
```

The path is correct though and has the templates.

As a workaround I copied the templates by hand. But it would be nice to have this working. I don't know though, where to start looking for a solution for this. Any ideas?

**Comment by tvdeyen** [comment]
@wdspkr maybe declaring `source_root`, [like in the Alchemy views generator](https://github.com/AlchemyCMS/alchemy_cms/blob/master/lib/rails/generators/alchemy/views/views_generator.rb#L20) helps

**Comment by wdspkr** [comment]
@tvdeyen That works indeed! Fix in https://github.com/AlchemyCMS/alchemy-pg_search/pull/9
